export const assets = {
  headerStickyNote: "/assets/header-sticky-note.png",
  calendarIcon: "/assets/calendar.svg",
  mariPortrait: "/assets/mari.png",
  ilyaPortrait: "/assets/ilya.png",
  hero: {
    mariVector9: "/assets/hero/mari-vector9.svg",
    mariVector5: "/assets/hero/mari-vector5.svg",
    ilyaVector8: "/assets/hero/ilya-vector8.svg",
    ilyaVector3: "/assets/hero/ilya-vector3.svg",
    ilyaVector7: "/assets/hero/ilya-vector7.svg",
    ilyaVector10: "/assets/hero/ilya-vector10.svg",
    ilyaEllipse3: "/assets/hero/ilya-ellipse3.svg",
    ilyaEllipse4: "/assets/hero/ilya-ellipse4.svg",
    ilyaEllipse5: "/assets/hero/ilya-ellipse5.svg",
    ilyaEllipse6: "/assets/hero/ilya-ellipse6.svg",
    ilyaEllipse7: "/assets/hero/ilya-ellipse7.svg",
    ilyaEllipse8: "/assets/hero/ilya-ellipse8.svg",
    ilyaEllipse9: "/assets/hero/ilya-ellipse9.svg",
    ilyaEllipse10: "/assets/hero/ilya-ellipse10.svg",
    ilyaEllipse11: "/assets/hero/ilya-ellipse11.svg",
  },
  calendarIllustration: "/assets/calendar-illustration.png",
  venueIllustration: "/assets/venue.png",
  programGuests: "/assets/program-guests.png",
  programCeremony: "/assets/program-ceremony.png",
  programBanquet: "/assets/program-banquet.png",
  programCake: "/assets/program-cake.png",
  womensOutfits: "/assets/womens-outfits.png",
  mensOutfits: "/assets/mens-outfits.png",
  moneyEnvelope: "/assets/money-envelope.png",
  flower: "/assets/flower.png",
  cats: "/assets/cats.png",
  pinIcon: "/assets/pin.svg",
  underline: "/assets/underline.png",
} as const;
