export const assets = {
  headerStickyNote: "/assets/header-sticky-note.webp",
  calendarIcon: "/assets/calendar.svg",
  mariPortrait: "/assets/mari.webp",
  ilyaPortrait: "/assets/ilya.webp",
  calendarIllustration: "/assets/calendar-illustration.webp",
  venueIllustration: "/assets/venue.webp",
  programGuests: "/assets/program-guests.webp",
  programCeremony: "/assets/program-ceremony.webp",
  programBanquet: "/assets/program-banquet.webp",
  programCake: "/assets/program-cake.webp",
  womensOutfits: "/assets/womens-outfits.webp",
  mensOutfits: "/assets/mens-outfits.webp",
  moneyEnvelope: "/assets/money-envelope.webp",
  flower: "/assets/flower.webp",
  cats: "/assets/cats.webp",
  pinIcon: "/assets/pin.svg",
  underline: "/assets/underline.webp",
} as const;
